name: Dispatch Trigger

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/**"

jobs:
  triggerDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: files
        run: |
          echo "frontend_changed=$(git diff --name-only HEAD~1 HEAD | grep 'frontend/' || echo '')" >> $GITHUB_ENV
          echo "backend_changed=$(git diff --name-only HEAD~1 HEAD | grep 'backend/' || echo '')" >> $GITHUB_ENV

      - name: Trigger Repository Dispatch for Frontend Changes
        if: env.frontend_changed != ''
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: frontend-changes
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: Trigger Repository Dispatch for Backend Changes
        if: env.backend_changed != ''
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: backend-changes
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
