name: Dispatch Trigger

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/**"
  workflow_dispatch:

jobs:
  triggerDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        shell: bash
        run: |
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            echo "frontend_changed=$(git diff --name-only HEAD~1 HEAD | grep 'frontend/' | tr '\n' ',' || echo '')" >> $GITHUB_ENV
            echo "backend_changed=$(git diff --name-only HEAD~1 HEAD | grep 'backend/' | tr '\n' ',' || echo '')" >> $GITHUB_ENV
          else
            echo "Checking all files since there's no previous commit."
            echo "frontend_changed=$(git ls-tree --name-only -r HEAD | grep 'frontend/' | tr '\n' ',' || echo '')" >> $GITHUB_ENV
            echo "backend_changed=$(git ls-tree --name-only -r HEAD | grep 'backend/' | tr '\n' ',' || echo '')" >> $GITHUB_ENV
          fi

      - name: Trigger Repository Dispatch for Frontend Changes
        if: env.frontend_changed != ''
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: frontend-changes
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: Trigger Repository Dispatch for Backend Changes
        if: env.backend_changed != ''
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: backend-changes
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
